dir=/app/data/downloads
disk-cache=32M
file-allocation=prealloc
continue=true
max-concurrent-downloads=10
max-connection-per-server=16
min-split-size=10M
split=32
disable-ipv6=true
input-file=/app/data/aria2/aria2.session
save-session=/app/data/aria2/aria2.session
save-session-interval=60
enable-rpc=true
rpc-listen-all=true
rpc-allow-origin-all=true
rpc-listen-port=6800
rpc-secret=
follow-torrent=true
listen-port=51413
enable-dht=true
dht-listen-port=51413
bt-enable-lpd=true
enable-peer-exchange=true
peer-id-prefix=-TR2770-
user-agent=Transmission/2.77
seed-ratio=0
bt-seed-unverified=true
bt-save-metadata=true
bt-max-peers=0
enable-color=false
show-console-readout=false
summary-interval=0
log-level=warn